version: "3"

services:
  airflow:
    build: 
      context: ./airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080" 
    command: webserver

  spark:
    build:
      context: ./spark
    volumes:
      - ./spark/app:/app
